import type { Language } from "./i18n";

const en = {
  instrument: "Instrument", lyrics: "Lyrics", noLyrics: "No lyrics are associated with this track.",
  searchOnline: "Search online", providerUnavailable: "Musixmatch and LyricFind require a configured commercial connection.",
  importFile: "Import LRC or TTML", paste: "Paste lyrics", create: "Create manually", replace: "Replace from file",
  syncedNone: "Unsynchronized", syncedLine: "Line synchronized", syncedWord: "Word synchronized",
  local: "Local", follow: "Follow playback", offset: "Offset", reset: "Reset", loopSelection: "Loop selection",
  selectionHelp: "Click a line to seek. Shift-click another line to select a passage.", focused: "Focus mode",
  exitFocused: "Exit focus mode", sourceInfo: "Source information", attribution: "Attribution", copyright: "Copyright",
  edit: "Edit local lyrics", delete: "Delete lyrics", makeLocal: "Create an editable local copy", close: "Close",
  editorTitle: "Local lyrics", editorHelp: "Paste plain text, LRC, enhanced LRC, or TTML.", save: "Save",
  cancel: "Cancel", deleteTitle: "Delete these lyrics?", deleteHelp: "The lyrics document will be removed from this project.",
  loading: "Loading lyrics…", error: "Lyrics could not be loaded.", importError: "The lyrics format could not be read.",
  invalidTimestamp: "A synchronized timestamp is malformed. Use [mm:ss.xx] for lines and <mm:ss.xx> for words.",
  timestampOutOfRange: "A synchronized timestamp is outside the audio duration.",
  searchTitle: "Search free lyrics", searchPlaceholder: "Title and artist", search: "Search", noResults: "No matching lyrics found.",
  useLyrics: "Use these lyrics", synced: "Synchronized", plain: "Plain text", lrclibHelp: "Free search through LRCLIB. No account or API key required.",
  exportSynced: "Export synchronized LRC", exportMarkdown: "Export simple Markdown", exported: "Lyrics exported",
  navigationLyrics: "Lyrics", previousLine: "Previous lyric line", nextLine: "Next lyric line",
  navigationPending: "timed lyrics unavailable · using Time", loopSnapLyricsHelp: "Snap A and B to the nearest synchronized lyric line",
} as const;
type LyricsMessageKey = keyof typeof en;
type LyricsCatalog = Record<LyricsMessageKey, string>;

const fr: LyricsCatalog = {
  instrument: "Instrument", lyrics: "Paroles", noLyrics: "Aucune parole n’est associée à ce morceau.",
  searchOnline: "Rechercher en ligne", providerUnavailable: "Musixmatch et LyricFind nécessitent une connexion commerciale configurée.",
  importFile: "Importer LRC ou TTML", paste: "Coller des paroles", create: "Créer manuellement", replace: "Remplacer depuis un fichier",
  syncedNone: "Non synchronisées", syncedLine: "Synchronisées par ligne", syncedWord: "Synchronisées mot par mot",
  local: "Local", follow: "Suivre la lecture", offset: "Décalage", reset: "Réinitialiser", loopSelection: "Boucler la sélection",
  selectionHelp: "Cliquez sur une ligne pour vous déplacer. Maj-clic sur une autre ligne sélectionne un passage.", focused: "Mode concentré",
  exitFocused: "Quitter le mode concentré", sourceInfo: "Informations sur la source", attribution: "Attribution", copyright: "Copyright",
  edit: "Modifier les paroles locales", delete: "Supprimer les paroles", makeLocal: "Créer une copie locale modifiable", close: "Fermer",
  editorTitle: "Paroles locales", editorHelp: "Collez du texte, du LRC, du LRC enrichi ou du TTML.", save: "Enregistrer",
  cancel: "Annuler", deleteTitle: "Supprimer ces paroles ?", deleteHelp: "Le document de paroles sera retiré de ce projet.",
  loading: "Chargement des paroles…", error: "Impossible de charger les paroles.", importError: "Le format des paroles n’a pas pu être lu.",
  invalidTimestamp: "Un horodatage synchronisé est invalide. Utilisez [mm:ss.xx] pour les lignes et <mm:ss.xx> pour les mots.",
  timestampOutOfRange: "Un horodatage synchronisé dépasse la durée du morceau.",
  searchTitle: "Rechercher des paroles gratuites", searchPlaceholder: "Titre et artiste", search: "Rechercher", noResults: "Aucune parole correspondante trouvée.",
  useLyrics: "Utiliser ces paroles", synced: "Synchronisées", plain: "Texte simple", lrclibHelp: "Recherche gratuite via LRCLIB, sans compte ni clé API.",
  exportSynced: "Exporter en LRC synchronisé", exportMarkdown: "Exporter en Markdown simple", exported: "Paroles exportées",
  navigationLyrics: "Paroles", previousLine: "Ligne de paroles précédente", nextLine: "Ligne de paroles suivante",
  navigationPending: "paroles minutées indisponibles · mode Temps utilisé", loopSnapLyricsHelp: "Caler A et B sur la ligne de paroles synchronisée la plus proche",
};

const es: LyricsCatalog = { ...en, instrument: "Instrumento", lyrics: "Letras", noLyrics: "No hay letras asociadas a esta pista.", searchOnline: "Buscar en línea", importFile: "Importar LRC o TTML", paste: "Pegar letras", create: "Crear manualmente", replace: "Reemplazar desde archivo", syncedNone: "Sin sincronizar", syncedLine: "Sincronizadas por línea", syncedWord: "Sincronizadas palabra por palabra", follow: "Seguir reproducción", offset: "Desfase", reset: "Restablecer", loopSelection: "Repetir selección", focused: "Modo enfoque", exitFocused: "Salir del modo enfoque", sourceInfo: "Información de la fuente", edit: "Editar letras locales", delete: "Eliminar letras", makeLocal: "Crear una copia local editable", close: "Cerrar", editorTitle: "Letras locales", editorHelp: "Pega texto, LRC, LRC mejorado o TTML.", save: "Guardar", cancel: "Cancelar", deleteTitle: "¿Eliminar estas letras?", deleteHelp: "El documento de letras se eliminará de este proyecto.", loading: "Cargando letras…", error: "No se pudieron cargar las letras.", importError: "No se pudo leer el formato de letras.", providerUnavailable: "Musixmatch y LyricFind requieren una conexión comercial configurada.", local: "Local", selectionHelp: "Haz clic en una línea para ir a ella. Mayús-clic selecciona un pasaje.", attribution: "Atribución", copyright: "Copyright", navigationLyrics: "Letras", previousLine: "Línea anterior", nextLine: "Línea siguiente", navigationPending: "letras temporizadas no disponibles · usando Tiempo", loopSnapLyricsHelp: "Ajustar A y B a la línea sincronizada más cercana" };
const de: LyricsCatalog = { ...en, instrument: "Instrument", lyrics: "Songtext", noLyrics: "Diesem Titel ist kein Songtext zugeordnet.", searchOnline: "Online suchen", importFile: "LRC oder TTML importieren", paste: "Songtext einfügen", create: "Manuell erstellen", replace: "Aus Datei ersetzen", syncedNone: "Nicht synchronisiert", syncedLine: "Zeilenweise synchronisiert", syncedWord: "Wortweise synchronisiert", follow: "Wiedergabe folgen", offset: "Versatz", reset: "Zurücksetzen", loopSelection: "Auswahl wiederholen", focused: "Fokusmodus", exitFocused: "Fokusmodus verlassen", sourceInfo: "Quellinformationen", edit: "Lokalen Songtext bearbeiten", delete: "Songtext löschen", makeLocal: "Bearbeitbare lokale Kopie erstellen", close: "Schließen", editorTitle: "Lokaler Songtext", editorHelp: "Text, LRC, erweitertes LRC oder TTML einfügen.", save: "Speichern", cancel: "Abbrechen", deleteTitle: "Diesen Songtext löschen?", deleteHelp: "Das Songtextdokument wird aus diesem Projekt entfernt.", loading: "Songtext wird geladen…", error: "Songtext konnte nicht geladen werden.", importError: "Das Songtextformat konnte nicht gelesen werden.", providerUnavailable: "Musixmatch und LyricFind benötigen eine konfigurierte kommerzielle Verbindung.", local: "Lokal", selectionHelp: "Klicken Sie zum Springen auf eine Zeile. Umschalt-Klick wählt einen Abschnitt.", attribution: "Namensnennung", copyright: "Copyright", navigationLyrics: "Songtext", previousLine: "Vorherige Textzeile", nextLine: "Nächste Textzeile", navigationPending: "zeitcodierter Songtext nicht verfügbar · Zeit wird verwendet", loopSnapLyricsHelp: "A und B an der nächsten synchronisierten Textzeile einrasten" };
const pt: LyricsCatalog = { ...en, instrument: "Instrumento", lyrics: "Letras", noLyrics: "Nenhuma letra está associada a esta faixa.", searchOnline: "Pesquisar online", importFile: "Importar LRC ou TTML", paste: "Colar letras", create: "Criar manualmente", replace: "Substituir do arquivo", syncedNone: "Não sincronizadas", syncedLine: "Sincronizadas por linha", syncedWord: "Sincronizadas palavra por palavra", follow: "Seguir reprodução", offset: "Deslocamento", reset: "Redefinir", loopSelection: "Repetir seleção", focused: "Modo de foco", exitFocused: "Sair do modo de foco", sourceInfo: "Informações da fonte", edit: "Editar letras locais", delete: "Excluir letras", makeLocal: "Criar cópia local editável", close: "Fechar", editorTitle: "Letras locais", editorHelp: "Cole texto, LRC, LRC aprimorado ou TTML.", save: "Salvar", cancel: "Cancelar", deleteTitle: "Excluir estas letras?", deleteHelp: "O documento de letras será removido deste projeto.", loading: "Carregando letras…", error: "Não foi possível carregar as letras.", importError: "Não foi possível ler o formato das letras.", providerUnavailable: "Musixmatch e LyricFind exigem uma conexão comercial configurada.", local: "Local", selectionHelp: "Clique em uma linha para navegar. Shift-clique seleciona um trecho.", attribution: "Atribuição", copyright: "Copyright" };
const it: LyricsCatalog = { ...en, instrument: "Strumento", lyrics: "Testo", noLyrics: "Nessun testo è associato a questa traccia.", searchOnline: "Cerca online", importFile: "Importa LRC o TTML", paste: "Incolla testo", create: "Crea manualmente", replace: "Sostituisci da file", syncedNone: "Non sincronizzato", syncedLine: "Sincronizzato per riga", syncedWord: "Sincronizzato parola per parola", follow: "Segui riproduzione", offset: "Scostamento", reset: "Ripristina", loopSelection: "Ripeti selezione", focused: "Modalità concentrazione", exitFocused: "Esci dalla modalità concentrazione", sourceInfo: "Informazioni sulla fonte", edit: "Modifica testo locale", delete: "Elimina testo", makeLocal: "Crea una copia locale modificabile", close: "Chiudi", editorTitle: "Testo locale", editorHelp: "Incolla testo semplice, LRC, LRC avanzato o TTML.", save: "Salva", cancel: "Annulla", deleteTitle: "Eliminare questo testo?", deleteHelp: "Il documento del testo verrà rimosso dal progetto.", loading: "Caricamento testo…", error: "Impossibile caricare il testo.", importError: "Impossibile leggere il formato del testo.", providerUnavailable: "Musixmatch e LyricFind richiedono una connessione commerciale configurata.", local: "Locale", selectionHelp: "Fai clic su una riga per spostarti. Maiusc-clic seleziona un passaggio.", attribution: "Attribuzione", copyright: "Copyright" };
const zh: LyricsCatalog = { ...en, instrument: "乐器", lyrics: "歌词", noLyrics: "此曲目尚未关联歌词。", searchOnline: "在线搜索", importFile: "导入 LRC 或 TTML", paste: "粘贴歌词", create: "手动创建", replace: "从文件替换", syncedNone: "未同步", syncedLine: "逐行同步", syncedWord: "逐字同步", follow: "跟随播放", offset: "偏移", reset: "重置", loopSelection: "循环所选段落", focused: "专注模式", exitFocused: "退出专注模式", sourceInfo: "来源信息", edit: "编辑本地歌词", delete: "删除歌词", makeLocal: "创建可编辑的本地副本", close: "关闭", editorTitle: "本地歌词", editorHelp: "粘贴纯文本、LRC、增强 LRC 或 TTML。", save: "保存", cancel: "取消", deleteTitle: "删除这些歌词？", deleteHelp: "歌词文档将从此项目中移除。", loading: "正在加载歌词…", error: "无法加载歌词。", importError: "无法读取歌词格式。", providerUnavailable: "Musixmatch 和 LyricFind 需要已配置的商业连接。", local: "本地", selectionHelp: "点击歌词行可跳转。按住 Shift 点击可选择段落。", attribution: "署名", copyright: "版权" };
const ja: LyricsCatalog = { ...en, instrument: "楽器", lyrics: "歌詞", noLyrics: "この曲には歌詞が関連付けられていません。", searchOnline: "オンライン検索", importFile: "LRC または TTML を読み込む", paste: "歌詞を貼り付け", create: "手動で作成", replace: "ファイルから置換", syncedNone: "未同期", syncedLine: "行単位で同期", syncedWord: "単語単位で同期", follow: "再生を追跡", offset: "オフセット", reset: "リセット", loopSelection: "選択範囲をループ", focused: "集中モード", exitFocused: "集中モードを終了", sourceInfo: "ソース情報", edit: "ローカル歌詞を編集", delete: "歌詞を削除", makeLocal: "編集可能なローカルコピーを作成", close: "閉じる", editorTitle: "ローカル歌詞", editorHelp: "プレーンテキスト、LRC、拡張 LRC、TTML を貼り付けます。", save: "保存", cancel: "キャンセル", deleteTitle: "この歌詞を削除しますか？", deleteHelp: "歌詞文書がプロジェクトから削除されます。", loading: "歌詞を読み込み中…", error: "歌詞を読み込めませんでした。", importError: "歌詞形式を読み込めませんでした。", providerUnavailable: "Musixmatch と LyricFind には設定済みの商用接続が必要です。", local: "ローカル", selectionHelp: "行をクリックして移動します。Shift クリックで範囲を選択します。", attribution: "帰属", copyright: "著作権" };
const ko: LyricsCatalog = { ...en, instrument: "악기", lyrics: "가사", noLyrics: "이 트랙에 연결된 가사가 없습니다.", searchOnline: "온라인 검색", importFile: "LRC 또는 TTML 가져오기", paste: "가사 붙여넣기", create: "직접 만들기", replace: "파일에서 교체", syncedNone: "동기화되지 않음", syncedLine: "줄 단위 동기화", syncedWord: "단어 단위 동기화", follow: "재생 따라가기", offset: "오프셋", reset: "재설정", loopSelection: "선택 구간 반복", focused: "집중 모드", exitFocused: "집중 모드 종료", sourceInfo: "소스 정보", edit: "로컬 가사 편집", delete: "가사 삭제", makeLocal: "편집 가능한 로컬 복사본 만들기", close: "닫기", editorTitle: "로컬 가사", editorHelp: "일반 텍스트, LRC, 확장 LRC 또는 TTML을 붙여넣으세요.", save: "저장", cancel: "취소", deleteTitle: "이 가사를 삭제할까요?", deleteHelp: "가사 문서가 이 프로젝트에서 제거됩니다.", loading: "가사 불러오는 중…", error: "가사를 불러오지 못했습니다.", importError: "가사 형식을 읽을 수 없습니다.", providerUnavailable: "Musixmatch와 LyricFind는 구성된 상용 연결이 필요합니다.", local: "로컬", selectionHelp: "줄을 클릭하여 이동합니다. Shift-클릭으로 구간을 선택합니다.", attribution: "저작자 표시", copyright: "저작권" };
const ar: LyricsCatalog = { ...en, instrument: "الآلة", lyrics: "الكلمات", noLyrics: "لا توجد كلمات مرتبطة بهذا المقطع.", searchOnline: "البحث عبر الإنترنت", importFile: "استيراد LRC أو TTML", paste: "لصق الكلمات", create: "إنشاء يدوي", replace: "استبدال من ملف", syncedNone: "غير متزامنة", syncedLine: "متزامنة حسب السطر", syncedWord: "متزامنة حسب الكلمة", follow: "متابعة التشغيل", offset: "الإزاحة", reset: "إعادة ضبط", loopSelection: "تكرار التحديد", focused: "وضع التركيز", exitFocused: "الخروج من وضع التركيز", sourceInfo: "معلومات المصدر", edit: "تحرير الكلمات المحلية", delete: "حذف الكلمات", makeLocal: "إنشاء نسخة محلية قابلة للتحرير", close: "إغلاق", editorTitle: "كلمات محلية", editorHelp: "الصق نصًا أو LRC أو LRC محسنًا أو TTML.", save: "حفظ", cancel: "إلغاء", deleteTitle: "حذف هذه الكلمات؟", deleteHelp: "ستتم إزالة مستند الكلمات من هذا المشروع.", loading: "جارٍ تحميل الكلمات…", error: "تعذر تحميل الكلمات.", importError: "تعذر قراءة تنسيق الكلمات.", providerUnavailable: "يتطلب Musixmatch وLyricFind اتصالًا تجاريًا مهيأً.", local: "محلي", selectionHelp: "انقر على سطر للانتقال إليه. استخدم Shift والنقر لتحديد مقطع.", attribution: "الإسناد", copyright: "حقوق النشر" };
const hi: LyricsCatalog = { ...en, instrument: "वाद्य", lyrics: "बोल", noLyrics: "इस ट्रैक से कोई बोल जुड़े नहीं हैं।", searchOnline: "ऑनलाइन खोजें", importFile: "LRC या TTML आयात करें", paste: "बोल चिपकाएँ", create: "स्वयं बनाएँ", replace: "फ़ाइल से बदलें", syncedNone: "असिंक्रनाइज़्ड", syncedLine: "पंक्ति के अनुसार सिंक्रनाइज़्ड", syncedWord: "शब्द के अनुसार सिंक्रनाइज़्ड", follow: "प्लेबैक का अनुसरण", offset: "ऑफ़सेट", reset: "रीसेट", loopSelection: "चयन दोहराएँ", focused: "फ़ोकस मोड", exitFocused: "फ़ोकस मोड से बाहर", sourceInfo: "स्रोत जानकारी", edit: "स्थानीय बोल संपादित करें", delete: "बोल हटाएँ", makeLocal: "संपादन योग्य स्थानीय प्रति बनाएँ", close: "बंद करें", editorTitle: "स्थानीय बोल", editorHelp: "सादा पाठ, LRC, उन्नत LRC या TTML चिपकाएँ।", save: "सहेजें", cancel: "रद्द करें", deleteTitle: "ये बोल हटाएँ?", deleteHelp: "बोल दस्तावेज़ इस प्रोजेक्ट से हटा दिया जाएगा।", loading: "बोल लोड हो रहे हैं…", error: "बोल लोड नहीं हो सके।", importError: "बोल प्रारूप पढ़ा नहीं जा सका।", providerUnavailable: "Musixmatch और LyricFind के लिए कॉन्फ़िगर किया गया व्यावसायिक कनेक्शन चाहिए।", local: "स्थानीय", selectionHelp: "किसी पंक्ति पर जाने के लिए क्लिक करें। Shift-क्लिक से अंश चुनें।", attribution: "श्रेय", copyright: "कॉपीराइट" };
const id: LyricsCatalog = { ...en, instrument: "Instrumen", lyrics: "Lirik", noLyrics: "Tidak ada lirik yang terkait dengan trek ini.", searchOnline: "Cari online", importFile: "Impor LRC atau TTML", paste: "Tempel lirik", create: "Buat manual", replace: "Ganti dari file", syncedNone: "Tidak tersinkron", syncedLine: "Tersinkron per baris", syncedWord: "Tersinkron per kata", follow: "Ikuti pemutaran", offset: "Ofset", reset: "Atur ulang", loopSelection: "Ulangi pilihan", focused: "Mode fokus", exitFocused: "Keluar mode fokus", sourceInfo: "Informasi sumber", edit: "Edit lirik lokal", delete: "Hapus lirik", makeLocal: "Buat salinan lokal yang dapat diedit", close: "Tutup", editorTitle: "Lirik lokal", editorHelp: "Tempel teks biasa, LRC, LRC lanjutan, atau TTML.", save: "Simpan", cancel: "Batal", deleteTitle: "Hapus lirik ini?", deleteHelp: "Dokumen lirik akan dihapus dari proyek ini.", loading: "Memuat lirik…", error: "Lirik tidak dapat dimuat.", importError: "Format lirik tidak dapat dibaca.", providerUnavailable: "Musixmatch dan LyricFind memerlukan koneksi komersial yang dikonfigurasi.", local: "Lokal", selectionHelp: "Klik baris untuk berpindah. Shift-klik memilih bagian.", attribution: "Atribusi", copyright: "Hak cipta" };

const catalogs: Record<Language, LyricsCatalog> = { en, fr, es, de, pt, it, zh, ja, ko, ar, hi, id };
const navigationMessages: Record<Language, Partial<LyricsCatalog>> = {
  en: {},
  fr: {},
  es: { navigationLyrics: "Letras", previousLine: "Línea anterior", nextLine: "Línea siguiente", navigationPending: "letras temporizadas no disponibles · usando Tiempo", loopSnapLyricsHelp: "Ajustar A y B a la línea sincronizada más cercana", invalidTimestamp: "Una marca de tiempo sincronizada no es válida. Usa [mm:ss.xx] para líneas y <mm:ss.xx> para palabras.", timestampOutOfRange: "Una marca de tiempo sincronizada supera la duración del audio." },
  de: { navigationLyrics: "Songtext", previousLine: "Vorherige Textzeile", nextLine: "Nächste Textzeile", navigationPending: "zeitcodierter Songtext nicht verfügbar · Zeit wird verwendet", loopSnapLyricsHelp: "A und B an der nächsten synchronisierten Textzeile einrasten", invalidTimestamp: "Ein synchronisierter Zeitstempel ist ungültig. Verwenden Sie [mm:ss.xx] für Zeilen und <mm:ss.xx> für Wörter.", timestampOutOfRange: "Ein synchronisierter Zeitstempel liegt außerhalb der Audiodauer." },
  pt: { navigationLyrics: "Letras", previousLine: "Linha anterior", nextLine: "Próxima linha", navigationPending: "letras temporizadas indisponíveis · usando Tempo", loopSnapLyricsHelp: "Ajustar A e B à linha sincronizada mais próxima", invalidTimestamp: "Um marcador de tempo sincronizado é inválido. Use [mm:ss.xx] para linhas e <mm:ss.xx> para palavras.", timestampOutOfRange: "Um marcador de tempo sincronizado excede a duração do áudio." },
  it: { navigationLyrics: "Testo", previousLine: "Riga precedente", nextLine: "Riga successiva", navigationPending: "testo temporizzato non disponibile · uso di Tempo", loopSnapLyricsHelp: "Aggancia A e B alla riga sincronizzata più vicina", invalidTimestamp: "Un indicatore temporale sincronizzato non è valido. Usa [mm:ss.xx] per le righe e <mm:ss.xx> per le parole.", timestampOutOfRange: "Un indicatore temporale sincronizzato supera la durata dell’audio." },
  zh: { navigationLyrics: "歌词", previousLine: "上一行歌词", nextLine: "下一行歌词", navigationPending: "暂无定时歌词 · 使用时间模式", loopSnapLyricsHelp: "将 A 和 B 吸附到最近的同步歌词行", invalidTimestamp: "同步时间戳无效。行请使用 [mm:ss.xx]，单词请使用 <mm:ss.xx>。", timestampOutOfRange: "同步时间戳超出了音频时长。" },
  ja: { navigationLyrics: "歌詞", previousLine: "前の歌詞行", nextLine: "次の歌詞行", navigationPending: "時間付き歌詞なし · 時間モードを使用", loopSnapLyricsHelp: "A と B を最寄りの同期歌詞行に合わせる", invalidTimestamp: "同期タイムスタンプが無効です。行には [mm:ss.xx]、単語には <mm:ss.xx> を使用してください。", timestampOutOfRange: "同期タイムスタンプが音声の長さを超えています。" },
  ko: { navigationLyrics: "가사", previousLine: "이전 가사 줄", nextLine: "다음 가사 줄", navigationPending: "시간 정보 가사 없음 · 시간 모드 사용", loopSnapLyricsHelp: "A와 B를 가장 가까운 동기화 가사 줄에 맞추기", invalidTimestamp: "동기화 타임스탬프가 잘못되었습니다. 줄에는 [mm:ss.xx], 단어에는 <mm:ss.xx>를 사용하세요.", timestampOutOfRange: "동기화 타임스탬프가 오디오 길이를 벗어났습니다." },
  ar: { navigationLyrics: "الكلمات", previousLine: "سطر الكلمات السابق", nextLine: "سطر الكلمات التالي", navigationPending: "الكلمات المؤقتة غير متاحة · استخدام الوقت", loopSnapLyricsHelp: "محاذاة A وB مع أقرب سطر كلمات متزامن", invalidTimestamp: "الطابع الزمني المتزامن غير صالح. استخدم [mm:ss.xx] للأسطر و<mm:ss.xx> للكلمات.", timestampOutOfRange: "يتجاوز طابع زمني متزامن مدة الصوت." },
  hi: { navigationLyrics: "बोल", previousLine: "पिछली बोल पंक्ति", nextLine: "अगली बोल पंक्ति", navigationPending: "समयबद्ध बोल उपलब्ध नहीं · समय मोड उपयोग में", loopSnapLyricsHelp: "A और B को निकटतम सिंक्रनाइज़्ड बोल पंक्ति पर स्नैप करें", invalidTimestamp: "सिंक समय अमान्य है। पंक्तियों के लिए [mm:ss.xx] और शब्दों के लिए <mm:ss.xx> उपयोग करें।", timestampOutOfRange: "सिंक समय ऑडियो की अवधि से बाहर है।" },
  id: { navigationLyrics: "Lirik", previousLine: "Baris lirik sebelumnya", nextLine: "Baris lirik berikutnya", navigationPending: "lirik bertempo tidak tersedia · memakai Waktu", loopSnapLyricsHelp: "Tempelkan A dan B ke baris lirik tersinkron terdekat", invalidTimestamp: "Stempel waktu sinkron tidak valid. Gunakan [mm:ss.xx] untuk baris dan <mm:ss.xx> untuk kata.", timestampOutOfRange: "Stempel waktu sinkron melebihi durasi audio." },
};
export const lyricsTranslate = (language: Language, key: LyricsMessageKey): string => navigationMessages[language][key] ?? catalogs[language][key];
