import type { Language } from "./i18n";

const en = {
  markers: "Markers", add: "Add marker at playhead", empty: "Add a marker to identify a section.",
  label: "Name", start: "Start", end: "End", save: "Save", cancel: "Cancel", delete: "Delete marker",
  loop: "Loop this section", source: "Source chapter", detected: "Detected", user: "Personal",
  defaultLabel: "Marker", seek: "Go to marker", invalid: "Enter a valid name and time range.",
  navigation: "Marker", previous: "Previous marker", next: "Next marker", loopSnap: "Snap A and B to the nearest marker",
} as const;
type MarkerMessageKey = keyof typeof en;
type MarkerCatalog = Record<MarkerMessageKey, string>;

const fr: MarkerCatalog = { markers: "Marqueurs", add: "Ajouter un marqueur à la tête de lecture", empty: "Ajoutez un marqueur pour identifier une section.", label: "Nom", start: "Début", end: "Fin", save: "Enregistrer", cancel: "Annuler", delete: "Supprimer le marqueur", loop: "Boucler cette section", source: "Chapitre source", detected: "Détecté", user: "Personnel", defaultLabel: "Marqueur", seek: "Aller au marqueur", invalid: "Saisissez un nom et une plage temporelle valides.", navigation: "Marqueur", previous: "Marqueur précédent", next: "Marqueur suivant", loopSnap: "Caler A et B sur le marqueur le plus proche" };
const es: MarkerCatalog = { ...en, markers: "Marcadores", add: "Añadir marcador en la posición actual", empty: "Añade un marcador para identificar una sección.", label: "Nombre", start: "Inicio", end: "Fin", save: "Guardar", cancel: "Cancelar", delete: "Eliminar marcador", loop: "Repetir esta sección", source: "Capítulo de origen", detected: "Detectado", user: "Personal", defaultLabel: "Marcador", seek: "Ir al marcador", invalid: "Introduce un nombre y un intervalo válidos." };
const de: MarkerCatalog = { ...en, markers: "Marker", add: "Marker an der Abspielposition hinzufügen", empty: "Fügen Sie einen Marker hinzu, um einen Abschnitt zu kennzeichnen.", label: "Name", start: "Start", end: "Ende", save: "Speichern", cancel: "Abbrechen", delete: "Marker löschen", loop: "Diesen Abschnitt wiederholen", source: "Quellkapitel", detected: "Erkannt", user: "Persönlich", defaultLabel: "Marker", seek: "Zum Marker springen", invalid: "Geben Sie einen gültigen Namen und Zeitbereich ein." };
const pt: MarkerCatalog = { ...en, markers: "Marcadores", add: "Adicionar marcador na posição atual", empty: "Adicione um marcador para identificar uma seção.", label: "Nome", start: "Início", end: "Fim", save: "Salvar", cancel: "Cancelar", delete: "Excluir marcador", loop: "Repetir esta seção", source: "Capítulo de origem", detected: "Detectado", user: "Pessoal", defaultLabel: "Marcador", seek: "Ir para o marcador", invalid: "Insira um nome e intervalo de tempo válidos." };
const it: MarkerCatalog = { ...en, markers: "Marcatori", add: "Aggiungi marcatore alla posizione corrente", empty: "Aggiungi un marcatore per identificare una sezione.", label: "Nome", start: "Inizio", end: "Fine", save: "Salva", cancel: "Annulla", delete: "Elimina marcatore", loop: "Ripeti questa sezione", source: "Capitolo sorgente", detected: "Rilevato", user: "Personale", defaultLabel: "Marcatore", seek: "Vai al marcatore", invalid: "Inserisci un nome e un intervallo validi." };
const zh: MarkerCatalog = { ...en, markers: "标记", add: "在播放位置添加标记", empty: "添加标记以识别乐段。", label: "名称", start: "开始", end: "结束", save: "保存", cancel: "取消", delete: "删除标记", loop: "循环此乐段", source: "来源章节", detected: "已检测", user: "个人", defaultLabel: "标记", seek: "跳转到标记", invalid: "请输入有效的名称和时间范围。" };
const ja: MarkerCatalog = { ...en, markers: "マーカー", add: "再生位置にマーカーを追加", empty: "セクションを識別するマーカーを追加します。", label: "名前", start: "開始", end: "終了", save: "保存", cancel: "キャンセル", delete: "マーカーを削除", loop: "このセクションをループ", source: "ソースのチャプター", detected: "検出", user: "個人", defaultLabel: "マーカー", seek: "マーカーへ移動", invalid: "有効な名前と時間範囲を入力してください。" };
const ko: MarkerCatalog = { ...en, markers: "마커", add: "재생 위치에 마커 추가", empty: "구간을 식별할 마커를 추가하세요.", label: "이름", start: "시작", end: "끝", save: "저장", cancel: "취소", delete: "마커 삭제", loop: "이 구간 반복", source: "원본 챕터", detected: "감지됨", user: "개인", defaultLabel: "마커", seek: "마커로 이동", invalid: "유효한 이름과 시간 범위를 입력하세요." };
const ar: MarkerCatalog = { ...en, markers: "العلامات", add: "إضافة علامة عند موضع التشغيل", empty: "أضف علامة لتحديد مقطع.", label: "الاسم", start: "البداية", end: "النهاية", save: "حفظ", cancel: "إلغاء", delete: "حذف العلامة", loop: "تكرار هذا المقطع", source: "فصل المصدر", detected: "مكتشف", user: "شخصي", defaultLabel: "علامة", seek: "الانتقال إلى العلامة", invalid: "أدخل اسمًا ونطاقًا زمنيًا صالحين." };
const hi: MarkerCatalog = { ...en, markers: "मार्कर", add: "प्लेबैक स्थान पर मार्कर जोड़ें", empty: "किसी भाग को पहचानने के लिए मार्कर जोड़ें।", label: "नाम", start: "आरंभ", end: "अंत", save: "सहेजें", cancel: "रद्द करें", delete: "मार्कर हटाएँ", loop: "इस भाग को दोहराएँ", source: "स्रोत अध्याय", detected: "पहचाना गया", user: "व्यक्तिगत", defaultLabel: "मार्कर", seek: "मार्कर पर जाएँ", invalid: "मान्य नाम और समय सीमा दर्ज करें।" };
const id: MarkerCatalog = { ...en, markers: "Penanda", add: "Tambah penanda di posisi putar", empty: "Tambahkan penanda untuk mengenali bagian.", label: "Nama", start: "Mulai", end: "Selesai", save: "Simpan", cancel: "Batal", delete: "Hapus penanda", loop: "Ulangi bagian ini", source: "Bab sumber", detected: "Terdeteksi", user: "Pribadi", defaultLabel: "Penanda", seek: "Ke penanda", invalid: "Masukkan nama dan rentang waktu yang valid." };

const catalogs: Record<Language, MarkerCatalog> = { en, fr, es, de, pt, it, zh, ja, ko, ar, hi, id };
export const markerTranslate = (language: Language, key: MarkerMessageKey): string => catalogs[language][key];
