"""Audit SonArcan neural networks before lowering them to ExecuTorch.

By default this script stops at ``torch.export``, the common backend-independent
contract required by ExecuTorch. Setting ``SONARCAN_EXECUTORCH_BACKEND`` to
``portable``, ``xnnpack``, ``coreml``, ``mlx``, ``metal``, or ``cuda`` additionally lowers real checkpoints
and writes optional PTE artifacts for release-builder qualification.

The checkpoints remain external release inputs.  Nothing generated by this
script is bundled in the desktop application.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
from types import MethodType
from typing import Any

import torch


ROOT = Path(__file__).resolve().parents[1]
LV_CONVOLUTION_CHUNK = 64
LV_CLASSIFIER_CHUNK = 64
LV_RECURRENT_CHUNKS = (64, 16, 4, 1)
DEFAULT_APP_MODELS = (
    Path.home()
    / "Library/Application Support/music.sonarcan.desktop/models"
)


def _tree_max_error(reference: Any, candidate: Any) -> float:
    reference_flat, reference_spec = torch.utils._pytree.tree_flatten(reference)
    candidate_flat, candidate_spec = torch.utils._pytree.tree_flatten(candidate)
    if reference_spec != candidate_spec or len(reference_flat) != len(candidate_flat):
        raise RuntimeError("the exported model changed its output structure")
    errors = []
    for expected, actual in zip(reference_flat, candidate_flat, strict=True):
        if not isinstance(expected, torch.Tensor) or not isinstance(actual, torch.Tensor):
            if expected != actual:
                raise RuntimeError("the exported model changed a non-tensor output")
            continue
        errors.append(float((expected - actual).abs().max().item()))
    return max(errors, default=0.0)


def _lower(
    exported: torch.export.ExportedProgram, backend_override: str | None = None
) -> tuple[bytes, str] | None:
    backend = backend_override or os.environ.get("SONARCAN_EXECUTORCH_BACKEND")
    if backend is None and os.environ.get("SONARCAN_EXECUTORCH_LOWER") == "1":
        backend = "portable"
    if backend is None:
        return None

    from executorch.exir import to_edge_transform_and_lower

    compile_config = None
    if backend == "portable":
        partitioners = None
    elif backend == "xnnpack":
        from executorch.backends.xnnpack.partition.xnnpack_partitioner import (
            XnnpackPartitioner,
        )

        partitioners = [XnnpackPartitioner()]
    elif backend == "coreml":
        from executorch.backends.apple.coreml.compiler import CoreMLBackend
        from executorch.backends.apple.coreml.partition import CoreMLPartitioner

        partitioners = [
            CoreMLPartitioner(
                compile_specs=CoreMLBackend.generate_compile_specs(),
                lower_full_graph=False,
                take_over_mutable_buffer=False,
            )
        ]
    elif backend == "mlx":
        from executorch.backends.mlx import MLXPartitioner

        partitioners = [MLXPartitioner()]
    elif backend == "metal":
        from executorch.backends.apple.metal.metal_backend import MetalBackend
        from executorch.backends.apple.metal.metal_partitioner import MetalPartitioner

        partitioners = [
            MetalPartitioner(
                [MetalBackend.generate_method_name_compile_spec("forward")]
            )
        ]
    elif backend == "cuda":
        from executorch.backends.cuda.cuda_backend import CudaBackend
        from executorch.backends.cuda.cuda_partitioner import CudaPartitioner
        from executorch.exir import EdgeCompileConfig

        partitioners = [
            CudaPartitioner(
                [CudaBackend.generate_method_name_compile_spec("forward")]
            )
        ]
        compile_config = EdgeCompileConfig(_check_ir_validity=False)
    else:
        raise ValueError(f"unsupported ExecuTorch backend: {backend}")

    arguments = {"partitioner": partitioners}
    if compile_config is not None:
        arguments["compile_config"] = compile_config
    program = to_edge_transform_and_lower(exported, **arguments).to_executorch()
    return bytes(program.buffer), backend


def _capture(
    name: str,
    model: torch.nn.Module,
    inputs: tuple[torch.Tensor, ...],
    *,
    lower: bool = True,
    backend: str | None = None,
    dynamic_shapes: Any = None,
    parity_inputs: tuple[torch.Tensor, ...] | None = None,
) -> dict[str, Any]:
    model.eval()
    with torch.inference_mode():
        expected = model(*inputs)
    exported = torch.export.export(
        model, inputs, dynamic_shapes=dynamic_shapes, strict=True
    )
    with torch.inference_mode():
        actual = exported.module()(*inputs)
    error = _tree_max_error(expected, actual)
    if error > 1e-5:
        raise RuntimeError(f"{name} export parity drifted by {error}")
    if parity_inputs is not None:
        with torch.inference_mode():
            parity_expected = model(*parity_inputs)
            parity_actual = exported.module()(*parity_inputs)
        parity_error = _tree_max_error(parity_expected, parity_actual)
        if parity_error > 1e-5:
            raise RuntimeError(f"{name} dynamic export parity drifted by {parity_error}")
        error = max(error, parity_error)
    report: dict[str, Any] = {
        "model": name,
        "nodes": len(tuple(exported.graph.nodes)),
        "maxAbsError": error,
    }
    lowered = _lower(exported, backend) if lower else None
    if lowered is not None:
        payload, selected_backend = lowered
        report["backend"] = selected_backend
        report["pteBytes"] = len(payload)
        report["pteSha256"] = hashlib.sha256(payload).hexdigest()
        if output_root := os.environ.get("SONARCAN_EXECUTORCH_OUTPUT_DIR"):
            destination = Path(output_root).resolve() / f"{name}.pte"
            destination.parent.mkdir(parents=True, exist_ok=True)
            temporary = destination.with_suffix(".pte.tmp")
            temporary.write_bytes(payload)
            temporary.replace(destination)
            report["ptePath"] = str(destination)
    return report


def audit_beat_this(checkpoint: Path) -> dict[str, Any]:
    from beat_this.inference import load_model
    from rotary_embedding_torch import RotaryEmbedding

    model = load_model(str(checkpoint), torch.device("cpu"))
    # Beat This processes fixed 1500-frame windows in production. Disabling its
    # opportunistic rotary cache removes an observable buffer mutation without
    # changing the computed frequencies, which is required by AOT runtimes.
    # Its einsum is only an outer product, but Core ML interprets this spelling
    # as a rank-changing permutation. Express the same operation by broadcasting
    # and verify it before replacing the export-only method.
    max_rotary_error = 0.0
    for module in model.modules():
        if isinstance(module, RotaryEmbedding):
            module.cache_if_possible = False
            positions = module.get_seq_pos(1500, device=torch.device("cpu"))
            with torch.inference_mode():
                expected = module(positions, seq_len=1500)

            def export_forward(self, t, seq_len=None, offset=0):
                del seq_len, offset
                frequencies = t.type(self.freqs.dtype).unsqueeze(-1) * self.freqs
                return torch.repeat_interleave(frequencies, 2, dim=-1)

            module.forward = MethodType(export_forward, module)
            with torch.inference_mode():
                actual = module(positions, seq_len=1500)
            max_rotary_error = max(
                max_rotary_error, float((expected - actual).abs().max().item())
            )
    if max_rotary_error > 1e-7:
        raise RuntimeError(f"Beat This rotary export adapter drifted by {max_rotary_error}")
    selected_backend = os.environ.get("SONARCAN_EXECUTORCH_BACKEND")
    # Core ML 9 can lower a dynamic Beat This graph but E5RT rejects it at
    # runtime because a pair of internal tensors remain data-dependent. Keep
    # Core ML fixed and use one dynamic XNNPACK program for short inputs and
    # fallback instead of duplicating a ladder of bucket PTEs.
    if selected_backend in {"coreml", "mlx", "metal", "cuda"}:
        report = _capture("beat-this", model, (torch.zeros((1, 1500, 128)),))
        report["minimumFrames"] = 1500
        report["maximumFrames"] = 1500
    else:
        frame_count = torch.export.Dim("beat_this_frames", min=13, max=1500)
        report = _capture(
            "beat-this",
            model,
            (torch.zeros((1, 1500, 128)),),
            dynamic_shapes=({1: frame_count},),
            parity_inputs=(torch.zeros((1, 257, 128)),),
        )
        report["minimumFrames"] = 13
        report["maximumFrames"] = 1500
    report["rotaryAdapterMaxAbsError"] = max_rotary_error
    return report


class _LVConvolutionChunk(torch.nn.Module):
    def __init__(self, convolution: torch.nn.Module):
        super().__init__()
        self.convolution = copy.deepcopy(convolution)

    def forward(self, value):
        return self.convolution(value)


class _LVRecurrentChunk(torch.nn.Module):
    def __init__(self, network: torch.nn.Module, *, reverse: bool):
        super().__init__()
        source = network.lstm1
        self.lstm = torch.nn.LSTM(
            input_size=source.input_size,
            hidden_size=source.hidden_size,
            num_layers=1,
            batch_first=True,
        )
        suffix = "_reverse" if reverse else ""
        with torch.no_grad():
            for name in ("weight_ih_l0", "weight_hh_l0", "bias_ih_l0", "bias_hh_l0"):
                getattr(self.lstm, name).copy_(getattr(source, f"{name}{suffix}"))

    def forward(self, value, hidden, cell):
        output, (next_hidden, next_cell) = self.lstm(value, (hidden, cell))
        return output, next_hidden, next_cell


class _LVClassifierChunk(torch.nn.Module):
    def __init__(self, network: torch.nn.Module):
        super().__init__()
        self.classifier = copy.deepcopy(network.final_fc1)

    def forward(self, value):
        return self.classifier(value)


def _run_lv_convolution(
    convolution: _LVConvolutionChunk, value: torch.Tensor
) -> torch.Tensor:
    frame_count = value.shape[2]
    padded_frames = ((frame_count + LV_CONVOLUTION_CHUNK - 1) // LV_CONVOLUTION_CHUNK) * LV_CONVOLUTION_CHUNK
    padded = torch.nn.functional.pad(value, (0, 0, 1, padded_frames - frame_count + 1))
    outputs = [
        convolution(padded[:, :, cursor : cursor + LV_CONVOLUTION_CHUNK + 2])[:, :, 1 : LV_CONVOLUTION_CHUNK + 1]
        for cursor in range(0, padded_frames, LV_CONVOLUTION_CHUNK)
    ]
    return torch.cat(outputs, dim=2)[:, :, :frame_count]


def _run_lv_classifier(
    classifier: _LVClassifierChunk, value: torch.Tensor
) -> torch.Tensor:
    frame_count = value.shape[1]
    padded_frames = ((frame_count + LV_CLASSIFIER_CHUNK - 1) // LV_CLASSIFIER_CHUNK) * LV_CLASSIFIER_CHUNK
    padded = torch.nn.functional.pad(value, (0, 0, 0, padded_frames - frame_count))
    outputs = [
        classifier(padded[:, cursor : cursor + LV_CLASSIFIER_CHUNK])
        for cursor in range(0, padded_frames, LV_CLASSIFIER_CHUNK)
    ]
    return torch.cat(outputs, dim=1)[:, :frame_count]


def _run_lv_recurrent(recurrent: dict[int, _LVRecurrentChunk], features: torch.Tensor) -> torch.Tensor:
    hidden_size = next(iter(recurrent.values())).lstm.hidden_size
    hidden = torch.zeros((1, features.shape[0], hidden_size))
    cell = torch.zeros_like(hidden)
    outputs = []
    cursor = 0
    while cursor < features.shape[1]:
        count = next(size for size in LV_RECURRENT_CHUNKS if size <= features.shape[1] - cursor)
        output, hidden, cell = recurrent[count](
            features[:, cursor : cursor + count], hidden, cell
        )
        outputs.append(output)
        cursor += count
    return torch.cat(outputs, dim=1)


def _audit_lv_member(index: int, network: torch.nn.Module) -> dict[str, Any]:
    feature = network.audio_feature_block
    feature_layers = [
        (feature.conv1a, feature.norm1a, None),
        (feature.conv1b, feature.norm1b, None),
        (feature.conv1c, feature.norm1c, feature.pool1),
        (feature.conv2a, feature.norm2a, None),
        (feature.conv2b, feature.norm2b, None),
        (feature.conv2c, feature.norm2c, feature.pool2),
        (feature.conv3a, feature.norm3a, None),
        (feature.conv3b, feature.norm3b, feature.pool3),
        (feature.conv4a, feature.norm4a, None),
        (feature.conv4b, feature.norm4b, None),
    ]
    forward = {size: _LVRecurrentChunk(network, reverse=False).eval() for size in LV_RECURRENT_CHUNKS}
    backward = {size: _LVRecurrentChunk(network, reverse=True).eval() for size in LV_RECURRENT_CHUNKS}
    classifier = _LVClassifierChunk(network).eval()
    hidden_state = torch.zeros((1, 1, network.lstm1.hidden_size))
    cell_state = torch.zeros_like(hidden_state)
    nonzero_hidden = torch.full_like(hidden_state, 0.25)
    nonzero_cell = torch.full_like(cell_state, -0.125)
    classifier_input = torch.ones((1, LV_CLASSIFIER_CHUNK, network.hidden_dim1))
    programs = []
    for direction, modules in (("forward", forward), ("backward", backward)):
        for size, recurrent in modules.items():
            recurrent_input = torch.ones((1, size, network.lstm1.input_size))
            programs.append(_capture(
                f"lv-chordia-s{index}-{direction}-{size}", recurrent,
                (recurrent_input, hidden_state, cell_state),
                parity_inputs=(recurrent_input, nonzero_hidden, nonzero_cell),
            ))
    programs.append(_capture(
        f"lv-chordia-s{index}-classifier-{LV_CLASSIFIER_CHUNK}", classifier, (classifier_input,)
    ))

    # A 37-frame sequence deliberately exercises several recurrent chunk sizes.
    # Feature extraction and classification are frame-local, so their final
    # chunks may be padded and truncated. The recurrent tail uses the one-frame
    # program to preserve the exact bidirectional LSTM context.
    value = torch.ones((1, 37, 252))
    with torch.inference_mode():
        expected = network(value)
        feature_value = value.view((1, 1, value.shape[1], value.shape[2]))
        for layer_index, (source_convolution, normalization, pooling) in enumerate(
            feature_layers
        ):
            convolution = _LVConvolutionChunk(source_convolution).eval()
            example = torch.ones(
                (
                    1,
                    source_convolution.in_channels,
                    LV_CONVOLUTION_CHUNK + 2,
                    feature_value.shape[3],
                )
            )
            programs.append(
                _capture(
                    f"lv-chordia-s{index}-convolution-{layer_index}",
                    convolution,
                    (example,),
                )
            )
            feature_value = torch.nn.functional.selu(
                normalization(_run_lv_convolution(convolution, feature_value))
            )
            if pooling is not None:
                feature_value = pooling(feature_value)
        features = feature_value.transpose(1, 2).contiguous().view(
            (1, value.shape[1], feature.output_size)
        )
        forward_value = _run_lv_recurrent(forward, features)
        reversed_features = torch.flip(features, dims=(1,))
        backward_value = torch.flip(
            _run_lv_recurrent(backward, reversed_features), dims=(1,)
        )
        recurrent = torch.cat((forward_value, backward_value), dim=2)
        logits = _run_lv_classifier(classifier, recurrent).reshape((37, -1))
        widths = [output.shape[1] for output in expected]
        boundaries = []
        cursor = 0
        for width in widths[:-1]:
            cursor += width
            boundaries.append(cursor)
        actual = tuple(torch.tensor_split(logits, boundaries, dim=1))
    reconstruction_error = _tree_max_error(expected, actual)
    # Fixed-size convolution and recurrent kernels may accumulate in a
    # different order at chunk boundaries. The qualified tolerance remains
    # far below the decoder's decision margin and is checked again end-to-end.
    if reconstruction_error > 1e-4:
        raise RuntimeError(
            f"LV-Chordia member {index} chunk reconstruction drifted by "
            f"{reconstruction_error}"
        )
    return {
        "member": index,
        "programs": programs,
        "sequenceFrames": 37,
        "reconstructionMaxAbsError": reconstruction_error,
    }


def audit_lv_chordia() -> dict[str, Any]:
    from lv_chordia.chord_recognition import load_ensemble

    members = load_ensemble(False, device=torch.device("cpu"))
    reports = [
        _audit_lv_member(index, member.net) for index, member in enumerate(members)
    ]
    return {"model": "lv-chordia", "members": reports}


def audit_scnet(checkpoint: Path) -> dict[str, Any]:
    from scnet_infer.checkpoints import get_spec
    from scnet_infer.runtime import load_runtime_model

    spec = get_spec()
    model = load_runtime_model(spec, checkpoint, torch.device("cpu"))
    inputs = (torch.zeros((1, 2, spec.chunk_size)),)
    report = _capture("scnet", model, inputs, lower=False)
    if os.environ.get("SONARCAN_EXECUTORCH_BACKEND") is not None:
        _replace_group_norm_for_delegate(model)
        _replace_bidirectional_lstm_for_delegate(model)
        report["partitions"] = _audit_scnet_real_partitions(model, inputs[0])
    return report


class _DelegateGroupNorm(torch.nn.Module):
    """Exact GroupNorm spelling built from delegate-friendly tensor ops."""

    def __init__(self, source: torch.nn.GroupNorm, *, channel_last: bool = False):
        super().__init__()
        self.groups = source.num_groups
        self.eps = source.eps
        self.channel_last = channel_last
        self.weight = torch.nn.Parameter(source.weight.detach().clone()) if source.weight is not None else None
        self.bias = torch.nn.Parameter(source.bias.detach().clone()) if source.bias is not None else None

    def forward(self, value):
        if self.channel_last:
            value = value.transpose(1, 2)
        shape = value.shape
        grouped = value.reshape(shape[0], self.groups, -1)
        mean = grouped.mean(dim=-1, keepdim=True)
        variance = ((grouped - mean) ** 2).mean(dim=-1, keepdim=True)
        output = ((grouped - mean) * torch.rsqrt(variance + self.eps)).reshape(shape)
        affine_shape = (1, shape[1], *((1,) * (value.dim() - 2)))
        if self.weight is not None:
            output = output * self.weight.reshape(affine_shape)
        if self.bias is not None:
            output = output + self.bias.reshape(affine_shape)
        return output.transpose(1, 2) if self.channel_last else output


def _replace_group_norm_for_delegate(module: torch.nn.Module) -> None:
    for name, child in tuple(module.named_children()):
        if isinstance(child, torch.nn.GroupNorm):
            channel_last = child.__class__.__name__ == "MyGroupNorm"
            replacement = _DelegateGroupNorm(child, channel_last=channel_last)
            sample = torch.linspace(-1.0, 1.0, 2 * child.num_channels * 12)
            sample = (
                sample.reshape(2, 12, child.num_channels)
                if channel_last
                else sample.reshape(2, child.num_channels, 3, 4)
            )
            with torch.inference_mode():
                error = float((child(sample) - replacement(sample)).abs().max().item())
            if error > 1e-5:
                raise RuntimeError(f"delegate GroupNorm adapter drifted by {error}")
            setattr(module, name, replacement)
        else:
            _replace_group_norm_for_delegate(child)


class _DelegateBidirectionalLstm(torch.nn.Module):
    """Bidirectional LSTM without aten.flip, which MLX cannot lower."""

    def __init__(self, source: torch.nn.LSTM):
        super().__init__()
        options = dict(
            input_size=source.input_size,
            hidden_size=source.hidden_size,
            num_layers=1,
            bias=source.bias,
            batch_first=source.batch_first,
            dropout=0.0,
            bidirectional=False,
        )
        self.forward_lstm = torch.nn.LSTM(**options)
        self.backward_lstm = torch.nn.LSTM(**options)
        with torch.no_grad():
            for name in ("weight_ih_l0", "weight_hh_l0", "bias_ih_l0", "bias_hh_l0"):
                if hasattr(source, name):
                    getattr(self.forward_lstm, name).copy_(getattr(source, name))
                    getattr(self.backward_lstm, name).copy_(getattr(source, f"{name}_reverse"))

    def forward(self, value):
        forward, _ = self.forward_lstm(value)
        indices = torch.arange(value.shape[1] - 1, -1, -1, device=value.device)
        backward, _ = self.backward_lstm(value.index_select(1, indices))
        backward = backward.index_select(1, indices)
        return torch.cat((forward, backward), dim=-1), None


def _replace_bidirectional_lstm_for_delegate(module: torch.nn.Module) -> None:
    for name, child in tuple(module.named_children()):
        if isinstance(child, torch.nn.LSTM) and child.bidirectional and child.num_layers == 1:
            replacement = _DelegateBidirectionalLstm(child)
            sample = torch.linspace(-0.2, 0.2, 2 * 7 * child.input_size).reshape(2, 7, child.input_size)
            with torch.inference_mode():
                expected, _ = child(sample)
                actual, _ = replacement(sample)
                error = float((expected - actual).abs().max().item())
            if error > 1e-5:
                raise RuntimeError(f"delegate bidirectional LSTM adapter drifted by {error}")
            setattr(module, name, replacement)
        else:
            _replace_bidirectional_lstm_for_delegate(child)


class _SCNetEncoderBlock(torch.nn.Module):
    def __init__(self, block: torch.nn.Module):
        super().__init__()
        self.block = block

    def forward(self, value):
        output, skip, _lengths, _original_lengths = self.block(value)
        return output, skip


class _SCNetDecoderBlock(torch.nn.Module):
    def __init__(
        self,
        fusion: torch.nn.Module,
        upsample: torch.nn.Module,
        lengths: list[int],
        original_lengths: list[int],
    ):
        super().__init__()
        self.fusion = fusion
        self.upsample = upsample
        self.lengths = lengths
        self.original_lengths = original_lengths

    def forward(self, value, skip):
        # FusionLayer uses ``+=``. Give it an owned value so parity evaluation
        # cannot mutate the example input reused by torch.export.
        value = self.fusion(value.clone(), skip)
        return self.upsample(value, self.lengths, self.original_lengths)


def _audit_scnet_real_partitions(
    model: torch.nn.Module, audio: torch.Tensor
) -> list[dict[str, Any]]:
    """Lower every real-valued SCNet block around native FFT boundaries."""
    selected = {
        value.strip()
        for value in os.environ.get(
            "SONARCAN_EXECUTORCH_PARTITIONS", "encoder,dual-path,decoder,mask"
        ).split(",")
        if value.strip()
    }
    padding = model.hop_length - audio.shape[-1] % model.hop_length
    if (audio.shape[-1] + padding) // model.hop_length % 2 == 0:
        padding += model.hop_length
    padded = torch.nn.functional.pad(audio, (0, padding))
    flat = padded.reshape(-1, padded.shape[-1])
    stft_options = dict(model.stft_config)
    if (window := getattr(model, "window", None)) is not None:
        stft_options["window"] = window
    with torch.inference_mode():
        spectrum = torch.stft(flat, **stft_options, return_complex=True)
        real = torch.view_as_real(spectrum)
        value = real.permute(0, 3, 1, 2).reshape(
            real.shape[0] // model.audio_channels,
            real.shape[3] * model.audio_channels,
            real.shape[1],
            real.shape[2],
        )
        if (position := getattr(model, "pos_embed_f", None)) is not None:
            value = value + position[:, :, : value.shape[2], :]

    reports: list[dict[str, Any]] = []
    skips: list[torch.Tensor] = []
    lengths_stack: list[list[int]] = []
    original_lengths_stack: list[list[int]] = []
    for index, block in enumerate(model.encoder):
        wrapper = _SCNetEncoderBlock(block)
        if "encoder" in selected:
            reports.append(_capture(f"scnet-encoder-{index}", wrapper, (value,)))
        with torch.inference_mode():
            value, skip, lengths, original_lengths = block(value)
        skips.append(skip)
        lengths_stack.append([int(item) for item in lengths])
        original_lengths_stack.append([int(item) for item in original_lengths])

    for index, (block, conversion) in enumerate(
        zip(
            model.separation_net.dp_modules,
            model.separation_net.feature_conversion,
            strict=True,
        )
    ):
        # XNNPACK's graph partition search is prohibitively expensive for the
        # unrolled LSTM graph. Its CPU fallback remains portable, while Apple
        # and CUDA exports lower the recurrent block to their native delegate.
        selected_dual_index = os.environ.get("SONARCAN_EXECUTORCH_SCNET_DUAL_INDEX")
        if "dual-path" in selected and (
            selected_dual_index is None or int(selected_dual_index) == index
        ):
            reports.append(
                _capture(
                    f"scnet-dual-path-{index}",
                    block,
                    (value,),
                    backend=(
                        os.environ.get("SONARCAN_EXECUTORCH_SCNET_DUAL_BACKEND")
                        or (
                            "portable"
                            if os.environ.get("SONARCAN_EXECUTORCH_BACKEND") == "xnnpack"
                            else None
                        )
                    ),
                )
            )
        with torch.inference_mode():
            value = block(value)
            # ExecuTorch portable tensors are real-only at this boundary. The
            # native worker performs this fixed-axis FFT/IFFT operation.
            value = conversion(value)

    for index, (fusion, upsample) in enumerate(model.decoder):
        wrapper = _SCNetDecoderBlock(
            fusion,
            upsample,
            lengths_stack.pop(),
            original_lengths_stack.pop(),
        )
        skip = skips.pop()
        if "decoder" in selected:
            reports.append(
                _capture(f"scnet-decoder-{index}", wrapper, (value, skip))
            )
        with torch.inference_mode():
            value = wrapper(value, skip)

    if (
        "mask" in selected
        and (mask_layer := getattr(model, "mask_layer", None)) is not None
    ):
        reports.append(_capture("scnet-mask", mask_layer, (value,)))
    return reports


def _make_demucs_exportable(model: torch.nn.Module) -> None:
    """Remove inference-neutral Python checks and randomness from HTDemucs.

    The pinned model sets ``sin_random_shift`` to zero, so replacing
    ``randrange(1)`` with the literal zero is mathematically identical.  The
    padding assertions compare complete tensors and are useful while
    developing Demucs, but create data-dependent graph guards; release parity
    below still validates their resulting computation.
    """
    import demucs.htdemucs as htdemucs
    import math
    from demucs.transformer import CrossTransformerEncoder
    from torch.nn import functional as functional

    def export_pad1d(value, paddings, mode="constant", pad_value=0.0):
        length = value.shape[-1]
        padding_left, padding_right = paddings
        if mode == "reflect":
            max_pad = max(padding_left, padding_right)
            if length <= max_pad:
                extra_pad = max_pad - length + 1
                extra_right = min(padding_right, extra_pad)
                extra_left = extra_pad - extra_right
                paddings = (padding_left - extra_left, padding_right - extra_right)
                value = functional.pad(value, (extra_left, extra_right))
        return functional.pad(value, paddings, mode, pad_value)

    def deterministic_position(self, length, batch, channels, device):
        if self.emb != "sin" or self.sin_random_shift != 0:
            raise RuntimeError("the pinned HTDemucs positional embedding contract changed")
        position = torch.arange(length, device=device).view(-1, 1, 1)
        half = channels // 2
        dimension = torch.arange(half, device=device).view(1, 1, -1)
        scale = torch.exp(math.log(self.max_period) * (dimension / (half - 1)))
        phase = position / scale
        return torch.cat((torch.cos(phase), torch.sin(phase)), dim=-1)

    htdemucs.pad1d = export_pad1d
    CrossTransformerEncoder._get_pos_embedding = deterministic_position
    if getattr(model.crosstransformer, "sin_random_shift", None) != 0:
        raise RuntimeError("the pinned HTDemucs model unexpectedly enables positional randomness")


def audit_demucs(checkpoint: Path) -> dict[str, Any]:
    from scnet_infer.fast_demucs import _load_safe_torch_model

    model = _load_safe_torch_model(checkpoint, torch)
    _make_demucs_exportable(model)
    samples = int(float(model.segment) * int(model.samplerate))
    audio = torch.zeros((1, 2, samples))
    report = _capture("htdemucs", model, (audio,), lower=False)
    if os.environ.get("SONARCAN_EXECUTORCH_BACKEND") is not None:
        _replace_group_norm_for_delegate(model)
        report["neuralCore"] = _audit_demucs_neural_core(model, audio)
    return report


class _HTDemucsNeuralCore(torch.nn.Module):
    """Real-valued HTDemucs graph between native STFT and reconstruction."""

    def __init__(self, model: torch.nn.Module):
        super().__init__()
        self.model = model

    def forward(self, magnitude, mixture):
        from einops import rearrange

        model = self.model
        value = magnitude
        mean = value.mean(dim=(1, 2, 3), keepdim=True)
        std = value.std(dim=(1, 2, 3), keepdim=True)
        value = (value - mean) / (1e-5 + std)

        time_value = mixture
        time_mean = time_value.mean(dim=(1, 2), keepdim=True)
        time_std = time_value.std(dim=(1, 2), keepdim=True)
        time_value = (time_value - time_mean) / (1e-5 + time_std)

        saved = []
        saved_time = []
        lengths = []
        time_lengths = []
        for index, encode in enumerate(model.encoder):
            lengths.append(value.shape[-1])
            inject = None
            if index < len(model.tencoder):
                time_lengths.append(time_value.shape[-1])
                time_encoder = model.tencoder[index]
                time_value = time_encoder(time_value)
                if not time_encoder.empty:
                    saved_time.append(time_value)
                else:
                    inject = time_value
            value = encode(value, inject)
            if index == 0 and model.freq_emb is not None:
                frequencies = torch.arange(value.shape[-2], device=value.device)
                embedding = model.freq_emb(frequencies).t()[None, :, :, None]
                value = value + model.freq_emb_scale * embedding.expand_as(value)
            saved.append(value)

        if model.crosstransformer:
            if model.bottom_channels:
                batch, channels, frequencies, frames = value.shape
                value = rearrange(value, "b c f t -> b c (f t)")
                value = model.channel_upsampler(value)
                value = rearrange(
                    value, "b c (f t) -> b c f t", f=frequencies, t=frames
                )
                time_value = model.channel_upsampler_t(time_value)
            value, time_value = model.crosstransformer(value, time_value)
            if model.bottom_channels:
                batch, channels, frequencies, frames = value.shape
                value = rearrange(value, "b c f t -> b c (f t)")
                value = model.channel_downsampler(value)
                value = rearrange(
                    value, "b c (f t) -> b c f t", f=frequencies, t=frames
                )
                time_value = model.channel_downsampler_t(time_value)

        for index, decode in enumerate(model.decoder):
            value, pre = decode(value, saved.pop(), lengths.pop())
            offset = model.depth - len(model.tdecoder)
            if index >= offset:
                time_decoder = model.tdecoder[index - offset]
                time_length = time_lengths.pop()
                if time_decoder.empty:
                    pre = pre[:, :, 0]
                    time_value, _ = time_decoder(pre, None, time_length)
                else:
                    time_value, _ = time_decoder(
                        time_value, saved_time.pop(), time_length
                    )

        source_count = len(model.sources)
        value = value.view(
            value.shape[0], source_count, -1, magnitude.shape[-2], magnitude.shape[-1]
        )
        value = value * std[:, None] + mean[:, None]
        time_value = time_value.view(
            time_value.shape[0], source_count, -1, mixture.shape[-1]
        )
        time_value = time_value * time_std[:, None] + time_mean[:, None]
        return value, time_value


def _audit_demucs_neural_core(
    model: torch.nn.Module, audio: torch.Tensor
) -> dict[str, Any]:
    if not model.cac:
        raise RuntimeError("the pinned HTDemucs export requires complex-as-channels mode")
    with torch.inference_mode():
        spectrum = model._spec(audio)
        magnitude = model._magnitude(spectrum)
    core = _HTDemucsNeuralCore(model)
    report = _capture("htdemucs-neural-core", core, (magnitude, audio))

    with torch.inference_mode():
        expected = model(audio)
        frequency_value, time_value = core(magnitude, audio)
        estimated_spectrum = model._mask(spectrum, frequency_value)
        frequency_audio = model._ispec(estimated_spectrum, audio.shape[-1])
        actual = time_value + frequency_audio
    reconstruction_error = float((expected - actual).abs().max().item())
    if reconstruction_error > 1e-5:
        raise RuntimeError(
            f"HTDemucs split reconstruction drifted by {reconstruction_error}"
        )
    report["splitReconstructionMaxAbsError"] = reconstruction_error
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "models",
        nargs="*",
        choices=("beat-this", "lv-chordia", "scnet", "demucs"),
        default=("beat-this", "lv-chordia", "scnet", "demucs"),
    )
    parser.add_argument(
        "--model-root",
        type=Path,
        default=Path(os.environ.get("SONARCAN_MODEL_ROOT", DEFAULT_APP_MODELS)),
    )
    arguments = parser.parse_args()
    requested = arguments.models or ["beat-this", "lv-chordia", "scnet", "demucs"]
    paths = {
        "beat-this": ROOT / "src-tauri/resources/models/beat-this/final0.ckpt",
        "scnet": arguments.model_root / "stem-separation/scnet-large-starrytong-v1.0.9/SCNet-large_starrytong_fixed.ckpt",
        "demucs": arguments.model_root / "stem-separation/htdemucs-v4/955717e8-8726e21a.th",
    }
    reports = []
    for name in requested:
        if name in paths and not paths[name].is_file():
            raise FileNotFoundError(f"missing {name} checkpoint: {paths[name]}")
        if name == "beat-this":
            reports.append(audit_beat_this(paths[name]))
        elif name == "lv-chordia":
            reports.append(audit_lv_chordia())
        elif name == "scnet":
            reports.append(audit_scnet(paths[name]))
        else:
            reports.append(audit_demucs(paths[name]))
    print(json.dumps({"torch": torch.__version__, "exports": reports}, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
